if: tag IS blank

language: java

sudo: false

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.gradle

install:
  - chmod a+x ./travis-build.sh
  - chmod a+x ./gradlew

script:
  - ./travis-build.sh
